### ISSUE TITLE
offset is not explained anywhere

### ISSUE THREAD

**Issue by LoganDark** [Kqzz/MCsniperGO#12]
I have no idea what an offset is. Is it the time that the program waits after the username is free to try claiming it? Does it try to claim slightly early to account for network lag? What unit is it in? Seconds? Milliseconds? This offset is never explained anywhere. I just tried using 0.1 but I don't know if that's fine or not

**Comment by Kqzz** [comment]
> I didn't mention video so I'm not sure how that's relevant, but actually useful documentation would be nice. Even reading the source code I can't figure out what offset means.

if i feel like it i’ll write docs, but tbh i don’t really like writing docs and such.

**Comment by fknMega** [comment]
Guys you didn't say what's offset yet, help?

**Comment by itsunderscores** [comment]
Yeah what does the offset do? Lol.

**Comment by suvan1911** [comment]
the amount of milliseconds to send the request early so you can get it before others, but if you send it too early you wouldnt get it aswell so yeah just experiment with it to find a good offset, start with maybe 100?
