### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by LoganDark** [Kqzz/MCsniperGO#14]
```
[input] offset » 0.05
[info] » Sniping y1t at 2021/10/18 12:51:48

[info] » authenticating <censored> through ms auth
[success] » successfully authenticated <censored>
[success] » verified that <censored> can snipe
sniping in 21s
starting in 20s...
[info] » sent @ 12:51:48.0053
[info] » sent @ 12:51:48.0106
[info] » sent @ 12:51:48.0155
[info] » sent @ 12:51:48.0201
[info] » sent @ 12:51:48.0264
[info] » sent @ 12:51:48.0313
[info] » [400] received @ 12:51:48.1029 | est process @ 12:51:48.053
[info] » [400] received @ 12:51:48.1087 | est process @ 12:51:48.059
[info] » [400] received @ 12:51:48.1125 | est process @ 12:51:48.063
[info] » [400] received @ 12:51:48.1209 | est process @ 12:51:48.07
[info] » [400] received @ 12:51:48.128 | est process @ 12:51:48.077
[info] » [400] received @ 12:51:48.1392 | est process @ 12:51:48.085
```

In the log file, it is simply:

```
accounts
<censored>:<censored> | Type: microsoft prename account
logs
sent @ 12:51:48.0053
sent @ 12:51:48.0106
sent @ 12:51:48.0155
sent @ 12:51:48.0201
sent @ 12:51:48.0264
sent @ 12:51:48.0313
[400] received @ 12:51:48.1029
[400] received @ 12:51:48.1087
[400] received @ 12:51:48.1125
[400] received @ 12:51:48.1209
[400] received @ 12:51:48.128
[400] received @ 12:51:48.1392
```

I wish I could give you more useful info, but it seems that not even the log file actually contains response bodies, so we might never know what went wrong.

**Comment by Kqzz** [comment]
nothing went wrong, there's no reason to include response bodies.

**Comment by Kqzz** [comment]
oh yeah, you're receives were just way too late. u want those nearer to .05. and yes, there is are always many people going for every 3char dropping.

**Comment by LoganDark** [comment]
so I guess in my case the optimal offset would be -0.075 or so?

**Comment by LoganDark** [comment]
> the unit is ms. there’s absolutely no info anywhere. all the info is known by people in the discord, so, without being in the discord there’s almost no info.

That's obvious by this point, my question to you is, what are you going to do about it? Can you improve the documentation so that people can use the project easier?

**Comment by Kqzz** [comment]
also, experiment by sniping names you want.. no other way.

**Comment by LoganDark** [comment]
> also, experiment by sniping names you want.. no other way.

That's very expensive, I only have 1 try at this, lol... I just want a 3 letter prename for a new project
