### ISSUE TITLE
Issue with bearer

### ISSUE THREAD

**Issue by itsunderscores** [Kqzz/MCsniperGO#19]
I've tried to use the bearer token instead but I'm getting errors.

What's wrong with this format?
# bearer
bearer:eyJhbGciOiJIUzI1NiJ9.eyJ4dWlkIjoiMjUzNTQxNzY

Please give me the correct format as this isn't working and I've tried multiple syntax's.

**Comment by beakballs** [comment]
eyJhbGciOiJIUzI1NiJ9.eyJ4dWlkIjoiMjUzNTQxNzY:bearer

**Comment by suvan1911** [comment]
I hope thats not your actual token, Don't share your token with anyone

**Comment by Kqzz** [comment]
this issue is entirely invalid seeing as u didnt read the format, AND u probably just leaked ur bearer. dont leak ur bearer.
