### ISSUE TITLE
When trying to snipe failed to authenticate

### ISSUE THREAD

**Issue by Myshiro** [Kqzz/MCsniperGO#20]
Hi, my prename account does not work and it says 
successfully authenticated ________@gmail.com
[err] » failed to verify that _________@gmail.com can snipe: prename acc: account is not authenticated
[err] » _____________@gmail.com not ready to snipe

**Comment by Myshiro** [comment]
please help

**Comment by content** [comment]
Try to verify the location on your microsoft account in the 'Security' menu
