### ISSUE TITLE
MacOS Big Sur Problem w/ MCSniperGO @ryans#0344

### ISSUE THREAD

**Issue by clkzy** [Kqzz/MCsniperGO#22]
<img width="649" alt="Screen Shot 2021-12-02 at 7 32 37 AM" src="https://user-images.githubusercontent.com/64039340/144431831-419ec429-ed22-4e2c-96cb-16678d1f5aac.png">
<img width="785" alt="Screen Shot 2021-12-02 at 7 33 09 AM" src="https://user-images.githubusercontent.com/64039340/144431909-4c82661f-2b3f-4f5c-b5b9-ea87eb67906e.png">

ryan#0344 #support

**Comment by clkzy** [comment]
<img width="350" alt="Screen Shot 2021-12-02 at 10 32 00 AM" src="https://user-images.githubusercontent.com/64039340/144463266-c14028a2-3c8f-4477-a3b2-147730dfa744.png">

**Comment by talwat** [comment]
Have you done `chmod +x whatever`?

**Comment by clkzy** [comment]
@talwat check #support lol

**Comment by sneakers** [comment]
make sure ur in the directory first and run these commands

`sudo chmod +x whatever`
`./whatever`

should fix .
