### ISSUE TITLE
Offset settings

### ISSUE THREAD

**Issue by AidanDevs** [Kqzz/MCsniperGO#23]
Would a good idea for the offset be setting it to my ping to minecraft.net?

**Comment by talwat** [comment]
It might be better to set it to api.mojang.com, but offset has more factors than your ping. I would just make some tests, and adjust according to them.

**Comment by overestimate** [comment]
> It might be better to set it to api.mojang.com, but offset has more factors than your ping. I would just try to make some snipes, and adjust according to them.

that's the older api that isn't used for profile management anymore, you'd wanna check your latency to `api.minecraftservices.com` using a tool like [pjperez/httping](https://github.com/pjperez/httping) or [van heusden's httping](https://www.vanheusden.com/httping/). also, you are right about there being more factors, processing time for the api + database lookups can affect the time it takes to get a response
