### ISSUE TITLE
failed to grab droptime: failed to grab droptime with status 400 Bad Request and body "{"error":"username not dropping"}"

### ISSUE THREAD

**Issue by pexayt** [Kqzz/MCsniperGO#24]
I always get this Error: failed to grab droptime: failed to grab droptime with status 400 Bad Request and body "{"error":"username not dropping"}"

![Screenshot_1](https://user-images.githubusercontent.com/70817469/146819253-28cf69c8-9012-4398-8428-4c20bc681bf2.png)

**Comment by pexayt** [comment]
i fixed it with turning down my offset

**Comment by C0dins** [comment]
? makes no sense as the name 5oul has been the same since 2015 most likely you were going for another name and put that changing the offset has nothing to do with the name dropping.

**Comment by raydddd** [comment]
lol
