### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by pexayt** [Kqzz/MCsniperGO#25]
![image](https://user-images.githubusercontent.com/70817469/147143003-edb26d21-ebbb-41e1-8c99-78acbc0c5ce7.png)

does that mean that it failed to snipe? I tried 5 Names and i got nothing :(

**Comment by ToothbrushB** [comment]
Yes, 403 means you didn't get the name.
I think [this](https://mojang-api-docs.netlify.app/needs-auth/change-name.html) is the API the sniper uses if you want to look at that for more info.

**Comment by pexayt** [comment]
Could u tell me any tips? Like what Offset or any settings? I don’t get any name

**Comment by gobboo** [comment]
Get more accounts

**Comment by qkn** [comment]
The offset should be approximately 200 plus your age times four, then subtract your ping if the number is odd, otherwise leave it as it is.

**Comment by pexayt** [comment]
Now i tried it 20 times and i still got no name :(

**Comment by pexayt** [comment]
i think my offset setting is not good. I use 400
