### ISSUE TITLE
Sniper snipes 1 hour early

### ISSUE THREAD

**Issue by Ihavenoiqq** [Kqzz/MCsniperGO#30]
For some reason my sniper is off by 1 hour and I don't know why, its also only off by 1 hour on name mc but nothing else

**Comment by Ihavenoiqq** [comment]
Okay, I fixed the namemc and now its on my timezone but the sniper is still an hour off

**Comment by Kqzz** [comment]
your computers time must not be synced, doesn’t seem like a sniper issue.
