### ISSUE TITLE
cant even snipe

### ISSUE THREAD

**Issue by Hwilliams8548** [Kqzz/MCsniperGO#32]
# Bug Report
Something went wrong and should be reported.

## Description

Whenever I try to snipe I just get a 403.

## Steps to reproduce

I dont know if anyone else is having this problem so it may not be easy to preproduce 

## Expected result

Is what should have happened is that I should have gotten the name.

## Actual result

Instead I get an Error 403 which makes no sense because the program has been updated recently

## Complete output

```sh
I am so sorry but I closed my CMD window and handsniped a name on the account sense then. So I have no accounts to snipe left. 
It said something that had Error 403 in red in it.
```

**Comment by Kqzz** [comment]
nothing went wrong, you just didn't get the name.
