### ISSUE TITLE
idk what happened here

### ISSUE THREAD

**Issue by SNEIKICH** [Kqzz/MCsniperGO#33]
<img width="914" alt="Снимок экрана 2022-01-19 в 21 32 25" src="https://user-images.githubusercontent.com/68926902/150201163-c65e43e9-4bcc-4609-9b7f-b125b819b6e8.png">
pls help @Kqzz

**Comment by Kqzz** [comment]
name isn’t dropping

**Comment by SNEIKICH** [comment]
I'm an idiot, explain what it means

**Comment by SNEIKICH** [comment]
nvm I'm dumb. name I wanted to snipe was _I_ogs and I thought it was logs lol
