### ISSUE TITLE
Offset

### ISSUE THREAD

**Issue by Redmixsucks** [Kqzz/MCsniperGO#36]
Hello!

I'm new in the bot sniping community. From what i saw, claiming names by handsniping isn't worth trying nowadays, and wanted to try new method. But i have one question. I kind of know what offset is, but is there any way of checking the perfect delay in the program or on a webpage? If not, will custom offset from mcsniperpy be okay?

Thank you in advance,
Redmix

**Comment by Kqzz** [comment]
There isn't any way to find a perfect offset. Offset is something that you have to find out through trial and error. There's no formula or program that can perfectly determine your offset. Using your ping as a starting offset is a good way to do it, although it's just a baseline.

**Comment by Liza-Developer** [comment]
MCsniperGO has a ping command you can use to get a estimate to work with.. most of these values are given to you through math though they arent always accurate so like kqzz stated its best to work around the value and just find a good number that gets you names.

alot of people dont understand that another factor into names is the Mojang api itself, sometimes you can claim early sometimes you need to send later then usual, its very much so luck based.. not every singular delay will be consistent on every name you go for..

I hope that explained some stuff up ❤️
