### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by jaxhelp** [Kqzz/MCsniperGO#39]
I get a 403 error when trying to snipe a name. (Microsoft) I used a bearer token

**Comment by lSyrexl** [comment]
same

**Comment by 6uf** [comment]
403 means you attempted to snipe a username but failed to claim it. 403 is perfectly fine.

403 - missed snipe on a MFA acc (Microsoft)
400 - missed snipe on a GC acc (giftcard unclaimed profile)
401 - unauthorized
