### ISSUE TITLE
auto sniper not working

### ISSUE THREAD

**Issue by jaxhelp** [Kqzz/MCsniperGO#40]
I open cmd and type "MCsniperGO_2.96_windows_64-bit.exe as".
It returns with: "[fatal err] » failed to grab next 3c with status 522  and body ""
[input] press enter to exit »
![image_2022-03-24_171354](https://user-images.githubusercontent.com/74832826/160030069-75ea8dc8-365c-45be-ac61-1221d908e61c.png)
"

**Comment by overestimate** [comment]
@coolkidmacho hey, is your API fixed yet? I've heard it's down and I know of 2 snipers that broke so far

**Comment by coolkidmacho** [comment]
Its not broken i just need to pay for it, I'm in the process of doing that, I just don't have it rn.

**Comment by 6uf** [comment]
ur api killed mcsn auto sniper lolw. might as well just make my own api tbh
