### ISSUE TITLE
does anyone have a linux tutorial

### ISSUE THREAD

**Issue by QunatumCrafter** [Kqzz/MCsniperGO#41]
i need an ubuntu tutorial please

**Comment by 6uf** [comment]
apt install snap
snap install go --classic

git clone https://github.com/Kqzz/MCsniperGO

cd MCsniperGO
go run .

after that just use `go run . ` as the cmd to run the sniper, i dont really use mcsnipergo often but you could read the docs and ask in the discord for support.
