### ISSUE TITLE
I live in England so would my offset be 100 or what and do i meed the minecraft web to be on change username page or profile page 

### ISSUE THREAD

**Issue by Usernameisidk2** [Kqzz/MCsniperGO#86]
# Bug Report
Something went wrong and should be reported.

## Complete output

```sh
# START OUTPUT

# END OUTPUT
```

**Comment by Darmanitan** [comment]
Hello! Unfortunately, **MCsniperGO is no longer working.** Due to API changes with Minecraft, we no longer have the accurate droptime of a name, and therefore we cannot snipe anymore.
